// <auto-generated />
namespace ThueXe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addsort : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsort));
        
        string IMigrationMetadata.Id
        {
            get { return "202509070906044_add-sort"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
